### ISSUE TITLE
Force install on Ruby 3

### ISSUE THREAD

**Issue by kylekyle** [sdaubert/packetgen#110]
PacketGen 3.1.5 doesn't work on Ruby 3.0.0. I get kwarg errors. I went to file an issue, and saw that this has been fixed in PacketGen 3.1.7. For some reason, I have to force install 3.1.7 on Ruby 3.0. 

Any idea why I have to force the install? 3.1.5 works great on Ruby 3.0!

**Comment by sdaubert** [comment]
@kylekyle Thanks for using Packetgen.

I'm sorry for the late reply.
> For some reason, I have to force install 3.1.7 on Ruby 3.0.

What do you mean by 'force install'? What is the command you used?

**Comment by kylekyle** [comment]
If I run 

```bash 
$ gem install packetgen
``` 

It installs 3.1.5. If I run 

```bash 
$ gem install packetgen:3.1.7
```

I get an error because that version lists ruby versions it is comptible with, but excludes ruby 3. If I run 

```bash
$ gem install --force packetgen:3.1.7
```

It installs (and runs) great.

**Comment by sdaubert** [comment]
@kylekyle I have the same issu here.

This is due to pcaprub dependency:

- packetgen 3.1.5 depends on pcaprub 0.12, which declare a ruby version > 0,
- packetgen 3.1.7 depends on pcaprub 0.13, which declare a ruby version ~> 2.0.

So pcaprub 0.13 cannot install on ruby 3, and so packetgen 3.1.7 (see pcaprub/pcaprub#57).

I will release packetgen 3.1.8 with dependency on pcaprub 0.12 ASAP.
